management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: algotrade
    description: An algorithmic trading platform that allows users to create, backtest, and simulate trading strategies.
    author: Matteo Melis
    version: '@project.version@'
spring:
  profiles:
    active: dev